# Generated by Django 5.0.6 on 2026-06-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doses", "0001_initial"),
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doselog",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="medicines.medicine"
            ),
        ),
    ]
