# Generated by Django 5.0.6 on 2026-06-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doses", "0002_initial"),
        ("medicines", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doselog",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="doselog",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medicines.medicineschedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doselog",
            unique_together={("schedule", "scheduled_date", "scheduled_time")},
        ),
    ]
