# Generated by Django 5.0.6 on 2026-06-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doses", "0002_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_number", models.CharField(max_length=15)),
                ("message_sent", models.TextField()),
                ("ai_variables", models.JSONField(blank=True, default=dict)),
                (
                    "response_received",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Taken"),
                            ("2", "Reschedule"),
                            ("3", "Not Taken"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("response_time", models.DateTimeField(blank=True, null=True)),
                ("rescheduled_to", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("responded", "Responded"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dose_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doses.doselog"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
    ]
