# Generated by Django 5.0.6 on 2026-06-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escalation_level",
                    models.CharField(
                        choices=[
                            ("whatsapp_primary", "WhatsApp Primary Caretaker"),
                            ("whatsapp_secondary", "WhatsApp Secondary Caretaker"),
                            ("bot_call", "Bot Call"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=15)),
                ("message_sent", models.TextField()),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dose_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doses.doselog"
                    ),
                ),
            ],
        ),
    ]
